### ISSUE TITLE
Dynamic import with template strings does not work.

### ISSUE THREAD

**Issue by Willaiem** [wuba/metro-code-split#3]
Does this package give the possibility to make it work? 
In the documentation, I only found an example with components being lazy-loaded.
The following code will throw an error.

App.tsx
```js
import React from 'react';
import { View, Text } from 'react-native';

const names = {
  container: 'Container'
}

const Container = React.lazy(() => import(`./src/components/${names.container}`))

export default function App() {
  return (
    <View>
      <React.Suspense fallback={<Text>Loading...</Text>}>
        <Container />
      </React.Suspense>
    </View>
  );
}
```

Container.tsx
```js
import { View, Text } from "react-native";

export const Container = () => (
  <View>
    <Text>This is a container.</Text>
  </View>
)
```

<img src="https://user-images.githubusercontent.com/25301582/157297509-d1504b5f-ccf2-4916-8a99-e13bdd9609ba.png" height=50% width=50% />

**Comment by fitsfish2** [comment]
It's the nature of the specification, not our problem.

**Comment by Willaiem** [comment]
Meh. What a pity.
